### ISSUE TITLE
猜词响应被其他插件重复处理

### ISSUE THREAD

**Issue by Ikaleio** [araea/koishi-plugin-wordle-game#1]
如图，安装了 wordle-game 和 chatluna。

![BEC4EFACADB9DCB25FB1C6440FD0E072](https://github.com/user-attachments/assets/3e4debc6-82a0-4af5-a4c6-9ee8f9fedee4)

**Comment by araea** [comment]
- https://github.com/araea/koishi-plugin-wordle-game/blob/main/src/index.ts#L601
> 你可以在上面的代码文件中看到插件关于中间件的处理，当触发中间件的时候，会中断中间件。
> 同时，插件提供不使用中间件的配置项，当关闭后，仅使用指令 `wordlegame.猜 xxx` 或者相关指令别名才能触发功能。
![image](https://github.com/user-attachments/assets/d2b3299e-413d-4c22-87e1-80ec53374e7d)

## 简单来说就是该问题似乎与本插件无关，可以通过禁用本插件的中间件解决这个问题，也可以通过联系 chatluna 开发者解决问题。

**Comment by Ikaleio** [comment]
是的，似乎的确是 ChatLuna 的问题，我已经向他们发了 Issue。感谢！

**Comment by magisk317** [comment]
这个小问题确实有点意思，除了跟上述其他聊天插件冲突外，还跟其他预留关键字冲突，比如有次答案是clear，机器人死活不识别，后来才知道跟指令系统冲突了，不过使用`wordlegame.猜 xxx`确实可以解决，当时没想到
